# Generated by Django 5.1.4 on 2026-05-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
